### ISSUE TITLE
Cannot find module 'cheerio'

### ISSUE THREAD

**Issue by finnley** [cometlj/hexo-translate-title#21]
当使用 npm install hexo-translate-title --save 之后去使用hexo 命令会提示下面错误

**Cannot find module 'cheerio'**

➜  finnley.github.io hexo clean
ERROR Plugin load failed: hexo-translate-title
Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/finnley/finnley.github.io/node_modules/hexo-translate-title/lib/util.js:9:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/Users/finnley/finnley.github.io/node_modules/hexo/lib/hexo/index.js:280:23)
    at /Users/finnley/finnley.github.io/node_modules/hexo-translate-title/index.js:5:12
    at readFile.then.script 
INFO  Deleted database.
INFO  Deleted public folder.

**Comment by longsizhuo** [comment]
How to solve it?
