### ISSUE TITLE
ERROR Plugin load failed: hexo-translate-title Cannot find module 'request'

### ISSUE THREAD

**Issue by itning** [cometlj/hexo-translate-title#5]
```
ERROR Plugin load failed: hexo-translate-title
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (G:\ProjectData\WebstormProjects\itningblog\node_modules\hexo-translate-title\lib\util.js:5:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (G:\ProjectData\WebstormProjects\itningblog\node_modules\hexo\lib\hexo\index.js:219:21)
    at G:\ProjectData\WebstormProjects\itningblog\node_modules\hexo-translate-title\index.js:5:12
    at fs.readFile.then.script (G:\ProjectData\WebstormProjects\itningblog\node_modules\hexo\lib\hexo\index.js:232:12)
    at tryCatcher (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (G:\ProjectData\WebstormProjects\itningblog\node_modules\bluebird\js\release\promise.js:524:17)
```

**Comment by xxzj990** [comment]
@itning 
`npm install --save request`

**Comment by cometlj** [comment]
你好，因为使用了async/await，所以默认使用了`request-promise`库，看贴的错误是`ERROR Plugin load failed: hexo-translate-title`，是插件没有加载成功错误。试试重新安装下插件

```bash
npm install hexo-translate-title -S
```
